<?php

//list of bitgo wallets

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://104.207.150.28:3080/api/v1/wallet");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


curl_setopt($ch, CURLOPT_HTTPHEADER,array(
    'Authorization: Bearer v2xa053fc44c156f84c0b86e02a2044e07b8e3be6e6226c545cb18688e0e4d30d19',
    'Content-Type: application/json'
    ));

curl_setopt($ch, CURLOPT_HEADER, false);

  $result= curl_exec($ch);
  
 $data = json_decode($result);
 ini_set('xdebug.var_display_max_depth', 5);
ini_set('xdebug.var_display_max_children', 256);
ini_set('xdebug.var_display_max_data', 1024);
var_dump($data);

//echo $data->session->scope[5];

//echo $data->wallets[0]->label;
 if ($data->total ==0){
	  echo "No wallet Created";
  } else{
$value = $data->wallets[0] ;
 /* foreach($data as $key => $value) {
    echo $value->label . ", " . $value->id . "<br>";
  }*/
 
  $ba=array();
  
 foreach ($data->wallets as $b=>$ba) {

     echo   $id   = $ba->label.' '.$ba->permissions.'<br>';
    //    $name = $obj->group->name;
}

  }
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);





?>